### ISSUE TITLE
Community leader ID is hard-coded

### ISSUE THREAD

**Issue by ijt** [Hylozoic/hylo-frontend#56]
In CommunityController.js, the leader ID is set to 21. This should probably be gotten from a user choice.

**Comment by edwardwest** [comment]
Interesting! I wonder what that is-- that's my Hylo ID --  so maybe it's
like a super-duper admin?

_______________________
*Edward West*
mobile 415.225.7335
Facebook <http://www.facebook.com/edwardjwest>  Twitter
<http://www.twitter.com/edwardwest>  LinkedIn
<http://www.linkedin.com/in/edwardwest>

**Comment by levity** [comment]
Yep-- it defaults Edward to be the community leader by default, as well as uses some copy he came up with for the welcome message. This is used only for the purposes of onboarding so it didn't make sense to build it out "properly" before we saw whether it was worth it (it turned out not to be).
