### ISSUE TITLE
It may make sense to move the 'toast' message to the bottom left

### ISSUE THREAD

**Issue by Connoropolous** [Hylozoic/hylo-frontend#70]
I think the bottom left of the screen is the place where people are getting used to seeing these 'toast' messages, when it comes to accessing an app through the web browser. It is where Google's material design places it, and where it shows up in many google web apps. It is just an idea to consider :)

**Comment by levity** [comment]
Sounds good to me! It'd be less likely to interfere with any controls in
the upper right too. Should just be a matter of tweaking the styles in
angular-growl.less if you (or anyone else out there) wants to do it.

**Comment by Connoropolous** [comment]
sweet. I may take a go at it :)

On Wed, Oct 21, 2015 at 10:29 AM, Lawrence Wang <notifications@github.com>
wrote:

> Sounds good to me! It'd be less likely to interfere with any controls in
> the upper right too. Should just be a matter of tweaking the styles in
> angular-growl.less if you (or anyone else out there) wants to do it.
>
> On Wed, Oct 21, 2015 at 10:18 AM Connor Turland <notifications@github.com>
> wrote:
>
> > I think the bottom left of the screen is the place where people are
> > getting used to seeing these 'toast' messages, when it comes to accessing
> > an app through the web browser. It is where Google's material design
> places
> > it, and where it shows up in many google web apps. It is just an idea to
> > consider :)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Hylozoic/hylo-frontend/issues/70>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hylozoic/hylo-frontend/issues/70#issuecomment-149969940>
> .
>



-- 
Connor Turland
~to craft a sustainable and thriving culture within and without myself~
co-creator of Metamaps.cc

**Comment by edwardwest** [comment]
thanks, Connor!

On Wednesday, October 21, 2015, Connor Turland <notifications@github.com>
wrote:

> sweet. I may take a go at it :)
>
> On Wed, Oct 21, 2015 at 10:29 AM, Lawrence Wang <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Sounds good to me! It'd be less likely to interfere with any controls in
> > the upper right too. Should just be a matter of tweaking the styles in
> > angular-growl.less if you (or anyone else out there) wants to do it.
> >
> > On Wed, Oct 21, 2015 at 10:18 AM Connor Turland <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > I think the bottom left of the screen is the place where people are
> > > getting used to seeing these 'toast' messages, when it comes to
> accessing
> > > an app through the web browser. It is where Google's material design
> > places
> > > it, and where it shows up in many google web apps. It is just an idea
> to
> > > consider :)
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/Hylozoic/hylo-frontend/issues/70>.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Hylozoic/hylo-frontend/issues/70#issuecomment-149969940
> >
> > .
> >
>
>
>
> --
> Connor Turland
> ~to craft a sustainable and thriving culture within and without myself~
> co-creator of Metamaps.cc
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hylozoic/hylo-frontend/issues/70#issuecomment-149997689>
> .
>


-- 
_______________________
*Edward West*
mobile 415.225.7335
Facebook <http://www.facebook.com/edwardjwest>  Twitter
<http://www.twitter.com/edwardwest>  LinkedIn
<http://www.linkedin.com/in/edwardwest>
