### ISSUE TITLE
Number of Members for communities is unset

### ISSUE THREAD

**Issue by Connoropolous** [Hylozoic/hylo-frontend#81]
<img width="237" alt="screen shot 2015-11-17 at 11 08 10 am" src="https://cloud.githubusercontent.com/assets/1409121/11216890/adbb9dbe-8d1b-11e5-86a5-729e8b8ddf1f.png">

**Comment by levity** [comment]
does this persist after a cache refresh?

**Comment by Connoropolous** [comment]
Nope, I see the numbers now :)
