### ISSUE TITLE
Text Box broken on Firefox 42.0 (Mac OS X)

### ISSUE THREAD

**Issue by simonv3** [Hylozoic/hylo-frontend#86]
I'm having a hard time creating new paragraphs. Seemingly randomly when typing a newline it won't let me start typing any other characters, and sometimes Enter doesn't work anymore either. Sometimes going up and down on the already typed text fixes it. 

(thought posting this here was more productive than hijacking a thread on Hylo).

**Comment by edwardwest** [comment]
Thanks, Simon-

We've now heard this a couple of times, and yet so far never been able to
duplicate-- does it happen all the time? or just sometimes?

Always Firefox, sometimes Windows 10, now Mac OS X...



On Saturday, November 21, 2015, Simon <notifications@github.com> wrote:

> I'm having a hard time creating new paragraphs. Seemingly randomly when
> typing a newline it won't let me start typing any other characters, and
> sometimes Enter doesn't work anymore either. Sometimes going up and down on
> the already typed text fixes it.
>
> (thought posting this here was more productive than hijacking a thread on
> Hylo).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hylozoic/hylo-frontend/issues/86>.
>


-- 
_______________________
*Edward West*
mobile 415.225.7335
Facebook <http://www.facebook.com/edwardjwest>  Twitter
<http://www.twitter.com/edwardwest>  LinkedIn
<http://www.linkedin.com/in/edwardwest>

**Comment by simonv3** [comment]
Hey @edwardwest 
Here's a video of a related error I guess? https://oasis.sandstorm.io/shared/CxRfBEN9C96uF2MlxgaQZXrlkG5KtKGkFot-JBe8FiS

I started recording this video hoping to recreate the problem (which I was able to do before recording), but this is something different from what I had already experienced. 

The console spits this out: 
```
Error: e is undefined
[2]</</</</<.setClass/k.promise<@https://d3ngex8q79bk55.cloudfront.net/assets/0f7e9086/bundle.min.js:1:12080
C/<@https://d3ngex8q79bk55.cloudfront.net/assets/0f7e9086/bundle.min.js:1:6123
Ue/this.$get</m.prototype.$digest@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.17/angular.min.js:124:514
Ue/this.$get</m.prototype.$apply@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.17/angular.min.js:127:10
l@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.17/angular.min.js:81:325
w@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.17/angular.min.js:85:449
Af/</I.onload@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.17/angular.min.js:86:462
nrWrapper@https://www.hylo.com/app:14:12489
```
But that's not while typing in the textbox, just on page load. 

Let me know if there's something else I can do to help you debug this!

**Comment by edwardwest** [comment]
Ok-- thank you so much-- we'll try to see what we can do--

Thanks again-
Edward
