### ISSUE TITLE
After pasting a link the cursor doesn't go to the end of the link

### ISSUE THREAD

**Issue by jdaviescoates** [Hylozoic/hylo-frontend#99]
If I post a link on Hylo the cursor stays where it is before the link, instead of after it, see e.g. this screen grab taken immediately after pasting a link:

![cursor_at_beginning_of_link_instead_of_end](https://cloud.githubusercontent.com/assets/2113743/13037266/ddf710a4-d374-11e5-81e9-dc3679e9ff84.png)

**Comment by edwardwest** [comment]
Thanks for catching all of these things, Josef!

The dev team is doing a rewrite of the front-end into React right now so
there will be a few things that get automagically fixed when that
happens... and probably a few new problems introduced.

If you want a preview of what's coming, you can check out next.hylo.com --
it's not yet feature-complete, and visual design is also not complete, but
it's going to be a much faster loading site with more real-time
interactions and auto-refresh. And, soon, it will also be visually
superior. :)

I really appreciate all your attention and support

_______________________
*Edward West*
mobile 415.225.7335
Facebook <http://www.facebook.com/edwardjwest>  Twitter
<http://www.twitter.com/edwardwest>  LinkedIn
<http://www.linkedin.com/in/edwardwest>
